### ISSUE TITLE
[FEAT] 코스 둘러보기 UI 구현

### ISSUE THREAD

**Issue by seuriseuljjeok** [seuriseuljjeok/DATEROAD-SwiftUI#11]
## 🛠 Issue

 코스 둘러보기 UI 구현

## 📝 To-do

- [x] 상단 네비바 UI 구현
- [x] 필터링 뷰 UI 구현
- [x] 코스 둘러보기 UI 구현
- [x] 필터링 로직 구현
- [x] 엠티뷰 UI 구현
- [x] 엠티뷰 로직 구현
- [x] 지역 바텀시트 UI 구현
- [x] 지역 필터링 로직 구현
