### ISSUE TITLE
[FEAT] 데이트 일정 둘러보기 UI 구현

### ISSUE THREAD

**Issue by seuriseuljjeok** [seuriseuljjeok/DATEROAD-SwiftUI#13]
## 🛠 Issue

데이트 일정 둘러보기 UI 구현

## 📝 To-do

- [x] 데이트 일정 둘러보기 UI 구현
- [x] 데이트 일정 엠티뷰 UI 구현
- [x] 데이트 일정 티켓 및 엠티뷰 로직 구현
