### ISSUE TITLE
[FEAT] 홈화면 UI 구현

### ISSUE THREAD

**Issue by seuriseuljjeok** [seuriseuljjeok/DATEROAD-SwiftUI#7]
## 🛠 Issue

홈화면 UI 구현

## 📝 To-do

- [x] 유저 정보 뷰 UI 구현
- [x] HOT 데이트 코스 뷰 UI 구현
- [x] 배너 뷰 UI 구현
- [x] 배너 무한 스크롤 및 자동 스크롤 구현
- [x] NEW 데이트 코스 뷰 UI 구현
